import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100">

      <body className={`${montserrat.className} antialiased p-2 flex flex-col `}>
        <Navbar />
        <div className="grid grid-cols-6 container mx-auto gap-2"  >
          {/* <div className="col-span-1" >
            <Sidebar />
          </div> */}
          <div className="col-span-6" >
            <div className="w-full">
              {children}

            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
